---
id: groonga-night-4
base_name: groonga-powered-by-2013
tags: []
presentation_date: 2013/11/29
version: 2013.11.29
licenses: []
slideshare_id:
speaker_deck_id: 
ustream_id: 
vimeo_id: 
author:
  markup_language: 
  name: HAYASHI Kentaro
  email: hayashi@clear-code.com
  rubygems_user: kenhys
  slideshare_user: kenhys
  speaker_deck_user: 
